### ISSUE TITLE
BlockREN token design

### ISSUE THREAD

**Issue by NutellaLicka** [TokelPlatform/tokel_brand#11]
# Details:
We are planning to give all BlockREN participants a conference/ticket/digital token for participating in the BlockREN conference. We need a graphic that can be used for the token. I am thinking that it should mimic physical tickets, but be digitized in a way. The idea is that it is a piece of memorabilia from the event that people can hold onto.

# Deadline:
31st of October

# Copy:
Potential ideas:
Make it look like a physical ticket, but with sponsor logos on it.
BlockREN specific details (TBA) time/location/information

**Comment by DreamTrims** [comment]
Is this still happening? I think not?

**Comment by kelcie33** [comment]
Supposed to be a big press release tomorrow.
