### ISSUE TITLE
Exchanges Template & AtomicDex images

### ISSUE THREAD

**Issue by DreamTrims** [TokelPlatform/tokel_brand#22]
It would be nice to have a template for when we join new exchanges.

It would also be ideal to have a few images for $TKL and AtomicDEX.

**Comment by kelcie33** [comment]
So there is already an issue open for Announcement templates, by have images for $TKL and AtomicDEX do you mean images of $TKL being on the AtomicDEX application? like in the portfolio?

**Comment by DreamTrims** [comment]
Yes, its like $TKL is available to buy, hold and trade in AtomicDEX type of messge.

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137257016-7a8bbb89-7b60-4284-8357-2f32efe540fb.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137257208-50ab98d9-cc89-408b-99de-13ff01ebc49a.png)

**Comment by kelcie33** [comment]
Moved to Drive 
https://drive.google.com/drive/folders/1ZW-GHxjoyFXexU9okVZrlKpV2ppCYtug?usp=sharing
