### ISSUE TITLE
Tokel Talk ANN with extra graphics

### ISSUE THREAD

**Issue by kelcie33** [TokelPlatform/tokel_brand#5]
Tokel Talk announcement copy

"The Tokel Platform will be hosting a Tokel Talk this weekend at 12pm UTC on the 11th of September.

Join our discord server to listen in.

We are looking for people to join our discord discussion event this weekend (12pm UTC Saturday) to discuss all things NFTs and tokenization. We will be discussing the TKL time-lock rewards plan, the IDO in general and the future of tokenizing digital and real world assets. We invite NFT/token creators, developers, enthusiasts and projects alike to join us. Please send me a DM if you're interested in joining."

**Comment by NutellaLicka** [comment]
https://www.figma.com/file/gd4hO8RqEvLP5afBTE75QH/Tokel-AMA?node-id=14%3A2
