### ISSUE TITLE
Rewards update ANN

### ISSUE THREAD

**Issue by kelcie33** [TokelPlatform/tokel_brand#8]
"Tokel time-lock rewards update
TKL sold: 3,000,000
Total time-lock pool: 17,000,000

For every 1 TKL you hold, you would receive:
Xyz TKL 

X on 15th June
Y on 15th March

**Comment by NutellaLicka** [comment]
Reason:
To inform people how much extra Tokel they can expect.

Copy: 
As you've listed. We will need a way for tim to update this each day to post it.

Deadline: 
12th September. We are looking to post it each day on the 12th, 13th, 14th & 15th.
