### ISSUE TITLE
General messages images

### ISSUE THREAD

**Issue by DreamTrims** [TokelPlatform/tokel_brand#9]
1) Messages

Tokel - Create NFTs & Tokens Easily
Tokel - Tokenize Everything
Tokel - Create A Token For Everything
Tokel - Tokenize The Future
Tokel - NFT Creation Platform
Tokel - NFT Universe
Tokel - NFT Galaxy, Token Universe
Tokel - Tokenization Redefined

2) Currency-based
$TKL 
The Currency of Tokenization

$TKL 
The Currency of NFTs

$TKL
The Token Economy currency

$TKL 
The Future of Tokenization

$TKL 
Tokenize everything

3) Generic

Generic images with the logo prominent and a variety of backgrounds.

**Comment by kelcie33** [comment]
![abstractlinesSquare-01 2](https://user-images.githubusercontent.com/10329007/135386413-87c3bcf8-4017-45fa-b05c-3e40bd4a7c1c.png)
![abstractlinesSquare-01 18](https://user-images.githubusercontent.com/10329007/135386418-ee0e6e49-8f40-4623-a5b1-eaf62196689b.png)
![abstractlinesSquare-01 19](https://user-images.githubusercontent.com/10329007/135386421-499004d5-2c71-4d2d-ac5e-c61bcca14871.png)
![abstractlinesSquare-01 20](https://user-images.githubusercontent.com/10329007/135386422-da704fd0-1fd6-424e-b0fe-e53759c1fe1d.png)
![abstractlinesSquare-01 21](https://user-images.githubusercontent.com/10329007/135386424-5b988ed3-8c84-40f3-a39b-63876cd2c1a0.png)
![abstractlinesSquare-01 22](https://user-images.githubusercontent.com/10329007/135386428-c9e677d2-c5cf-4d86-850d-25da2fdcc029.png)
![artboartorbit-01 3](https://user-images.githubusercontent.com/10329007/135386429-7bcab08c-610b-435b-b7cb-34868e17bd0d.png)
![artboartorbit-01 4](https://user-images.githubusercontent.com/10329007/135386432-1cdc20cf-56b2-46cb-bb49-e8ac0124acc6.png)
![artboartorbit-01 12](https://user-images.githubusercontent.com/10329007/135386434-1c08841a-02f5-474f-93a0-7379e7b86bf8.png)
![artboartorbit-01 13](https://user-images.githubusercontent.com/10329007/135386436-9c798e89-92cb-4476-bf78-436e00e431f8.png)
![artboartorbit-01 14](https://user-images.githubusercontent.com/10329007/135386437-091ccc01-ad04-445d-86aa-60f2ea12cdd3.png)
![artboartorbit-01 15](https://user-images.githubusercontent.com/10329007/135386440-f529656f-2e05-48c8-857a-2a765a6af9e1.png)
![Frame 24](https://user-images.githubusercontent.com/10329007/135386442-b3b9234d-60d8-4723-be95-3011c9c73e90.png)
![Frame 25](https://user-images.githubusercontent.com/10329007/135386444-8c9bd767-fef1-4e70-9aea-217631d2013f.png)
![Frame 26](https://user-images.githubusercontent.com/10329007/135386446-c651a253-6239-4856-94c9-61cf77a86783.png)
![Frame 27](https://user-images.githubusercontent.com/10329007/135386448-42b2d475-d8f1-41ed-be8a-13d97ffd5dda.png)
![Frame 28](https://user-images.githubusercontent.com/10329007/135386450-ca1d42a8-c8f3-43ab-9794-f5729ec8012f.png)
![Frame 30](https://user-images.githubusercontent.com/10329007/135386451-5c0bddcc-bfd7-4a0d-b112-9c55d42d5851.png)
![Frame 36](https://user-images.githubusercontent.com/10329007/135386452-24c4fdcc-eefd-4695-8d53-c4da18ceaa01.png)
![Frame 108](https://user-images.githubusercontent.com/10329007/135386453-824afde2-6cc8-44a1-b32c-4658ff0c1a71.png)
![Frame 109](https://user-images.githubusercontent.com/10329007/135386459-5512599e-0890-4317-942a-d7c750d05efa.png)
![Frame 131](https://user-images.githubusercontent.com/10329007/135386461-1a02c2cc-0ea7-43de-a0c2-7b515f7ab8f7.png)
![Frame 133](https://user-images.githubusercontent.com/10329007/135386463-9635ea10-8a30-4ee7-9a74-61b20f6eac51.png)
![Frame 134](https://user-images.githubusercontent.com/10329007/135386465-baf87b40-478a-453a-b7e1-9707625db371.png)
![Frame 135](https://user-images.githubusercontent.com/10329007/135386467-0eae09ff-ef74-4f22-af15-99d79d73b857.png)
![Frame 136](https://user-images.githubusercontent.com/10329007/135386469-d60d284a-1e59-457d-83cd-da46c76a86a8.png)
![Frame 137](https://user-images.githubusercontent.com/10329007/135386472-2ccc29da-9826-44c2-a6f2-68ff113622fe.png)
![Frame 138](https://user-images.githubusercontent.com/10329007/135386474-a2decf1f-975b-4972-84ce-df5cfaab4b2d.png)
![Frame 139](https://user-images.githubusercontent.com/10329007/135386476-68b2c64d-add9-494e-9123-718e04c852df.png)
![Frame 140](https://user-images.githubusercontent.com/10329007/135386478-0b41fd06-5bb7-4435-aed6-fbf3454f7638.png)
![Frame 141](https://user-images.githubusercontent.com/10329007/135386479-1366a696-55eb-41cb-9634-db073e4dc6be.png)
![Frame 142](https://user-images.githubusercontent.com/10329007/135386481-72c44134-409a-44d7-8e69-5fa8c49107f0.png)
![Frame 143](https://user-images.githubusercontent.com/10329007/135386484-47d66597-3116-4eb4-aaf2-9f74bc0792e3.png)
![Frame 144](https://user-images.githubusercontent.com/10329007/135386487-522c2283-0670-478c-828f-1e9b0b270d1f.png)
![Frame 145](https://user-images.githubusercontent.com/10329007/135386488-4251aa59-96cb-4b2f-a55d-f8c9edfa26ca.png)
![Frame 146](https://user-images.githubusercontent.com/10329007/135386489-4a8bdf33-7b89-4298-9711-8bff5af0fc31.png)
![Frame 148](https://user-images.githubusercontent.com/10329007/135386491-9f32a56e-f386-421d-8df7-3b9a7096b0f0.png)
![Frame 149](https://user-images.githubusercontent.com/10329007/135386493-cb96a7f7-4c41-4ba7-8de6-e1b7c6c7ae68.png)
![Frame 150](https://user-images.githubusercontent.com/10329007/135386495-4e08d9fd-b9e9-4d87-8fde-905094f52031.png)
![Frame 151](https://user-images.githubusercontent.com/10329007/135386497-482fb3e0-21a9-4bdf-a680-9cdf19524acd.png)
![Frame 152](https://user-images.githubusercontent.com/10329007/135386498-89a4fba5-029a-499b-92bd-f95e85e324d5.png)
![Frame 153](https://user-images.githubusercontent.com/10329007/135386501-c2dd9ce0-c371-44d8-9b96-62a576ad70bb.png)
![Frame 154](https://user-images.githubusercontent.com/10329007/135386503-29f063df-2e7d-4d98-94dc-66e3ecb28ea6.png)
![Frame 156](https://user-images.githubusercontent.com/10329007/135386504-e23abc1d-0aff-4925-abe8-89c83ce930b0.png)
![Frame 157](https://user-images.githubusercontent.com/10329007/135386506-340fc206-a3ec-454e-b205-ce8af8c59bf3.png)
![Frame 158](https://user-images.githubusercontent.com/10329007/135386507-a1bf401a-4f31-48e1-ba2c-dea5c9c5cd9e.png)
![Frame 159](https://user-images.githubusercontent.com/10329007/135386509-b9d8fd29-ce67-4405-9cbd-ba7b15bc808d.png)
![Frame 160](https://user-images.githubusercontent.com/10329007/135386511-c23b53ae-2696-4e77-ba95-ac3f64038d28.png)
![Frame 161](https://user-images.githubusercontent.com/10329007/135386513-bdea838f-6a1b-4f05-878a-a49c4091162a.png)
![Frame 162](https://user-images.githubusercontent.com/10329007/135386514-7c9ad44d-2e16-4e33-ac63-c83c20e6cba9.png)
![Frame 163](https://user-images.githubusercontent.com/10329007/135386515-50bc2151-582f-4a96-b829-61f4c66d6fe8.png)
![Frame 164](https://user-images.githubusercontent.com/10329007/135386517-bdf18125-ec27-4a6b-b39f-4ef80825a68d.png)
![Frame 165](https://user-images.githubusercontent.com/10329007/135386518-e8e896d5-011a-4ede-804d-7729626948a0.png)
![Frame 166](https://user-images.githubusercontent.com/10329007/135386520-9d62d221-17b7-452f-a408-0de59b42207e.png)
![Frame 167](https://user-images.githubusercontent.com/10329007/135386526-8d53f2d8-6f27-444b-9bf4-39c573773801.png)
![Frame 168](https://user-images.githubusercontent.com/10329007/135386529-c736485a-7fe6-47c6-9a00-7375f7c04885.png)
![Frame 169](https://user-images.githubusercontent.com/10329007/135386530-8f99b8bb-690b-4c5a-a065-aa570b9a8769.png)
![Frame 170](https://user-images.githubusercontent.com/10329007/135386531-12bea536-57bd-4f28-bfab-e9b523afa2b3.png)
![Group 175](https://user-images.githubusercontent.com/10329007/135386535-fba90322-0cbd-4671-b344-734a11e8bbca.png)
![Group 177](https://user-images.githubusercontent.com/10329007/135386536-e99be93d-7a12-41c7-8d55-f9781aef0b6e.png)
![Group 192](https://user-images.githubusercontent.com/10329007/135386537-35b7680b-e6c5-4371-94f4-787b3b65dc18.png)
![Group 193](https://user-images.githubusercontent.com/10329007/135386540-4e61d789-6487-45fe-8eb8-817374172dfc.png)
![Group 194](https://user-images.githubusercontent.com/10329007/135386543-ca0cabfc-4183-421d-83c1-d711fcc735ca.png)
![Group 195](https://user-images.githubusercontent.com/10329007/135386545-b2646a84-7e4c-4c6a-9cc2-14cbb67bf6e9.png)
![lineabstractmulti3color-01 2](https://user-images.githubusercontent.com/10329007/135386548-3dbe4ac1-c201-4d63-a313-e88608569b47.png)
![lineabstractmulti3color-01 3](https://user-images.githubusercontent.com/10329007/135386549-fad6ecf1-a4cf-454d-8fab-a9e0f9a34b63.png)
![lineabstractmulti3color-01 11](https://user-images.githubusercontent.com/10329007/135386552-55dc3c03-6b75-40ba-a62f-5d0f4d8c9736.png)
![lineabstractmulti3color-01 12](https://user-images.githubusercontent.com/10329007/135386554-5a87fe33-1ae0-437f-9fa3-ea535482b185.png)
![lineabstractmulti3color-01 13](https://user-images.githubusercontent.com/10329007/135386558-4ae7642a-71c6-4bde-83d6-c5236c30760c.png)
![lineabstractmulti3color-01 14](https://user-images.githubusercontent.com/10329007/135386560-9b3b6b27-9e6e-40f9-971a-b4c059d22994.png)
![lineabstractmultidotssmall-01 2](https://user-images.githubusercontent.com/10329007/135386561-1b51a34f-7ec5-4c85-8534-d6ba618c4a56.png)
![lineabstractmultidotssmall-01 11](https://user-images.githubusercontent.com/10329007/135386563-1e9288b9-ae05-408e-9fe0-294bfb820933.png)
![lineabstractmultidotssmall-01 12](https://user-images.githubusercontent.com/10329007/135386565-326d6caf-4a4d-4109-8306-4978f2555d46.png)
![lineabstractmultidotssmall-01 13](https://user-images.githubusercontent.com/10329007/135386566-08d38a28-2dfe-46fb-84de-996ec3314d98.png)
![lineabstractmultidotssmall-01 14](https://user-images.githubusercontent.com/10329007/135386567-e58fc5d3-7550-45c6-b68f-cb854ecd4b0b.png)
![lineabstractmultidotssmall-01 15](https://user-images.githubusercontent.com/10329007/135386569-1cda0f68-0c81-4688-b1b7-7ce6e43eab41.png)
![multicolororbit-01 2](https://user-images.githubusercontent.com/10329007/135386570-de67b3c6-b99f-4ddf-ba27-db30717706d9.png)
![multicolororbit-01 3](https://user-images.githubusercontent.com/10329007/135386572-5f432ead-b414-4781-bdc0-ffb380ee2ff7.png)
![multicolororbit-01 11](https://user-images.githubusercontent.com/10329007/135386576-655c2ded-64c4-49a7-a842-5a7071a3ec45.png)
![multicolororbit-01 12](https://user-images.githubusercontent.com/10329007/135386579-a30b87cc-e8d9-4f64-b367-242f04c95987.png)
![multicolororbit-01 13](https://user-images.githubusercontent.com/10329007/135386580-f99e5f30-f241-486a-9a81-d9a3170a345a.png)
![multicolororbit-01 14](https://user-images.githubusercontent.com/10329007/135386582-073222fd-df4b-4e12-a78a-c129ab663f52.png)
![rewardsupdates copy 5](https://user-images.githubusercontent.com/10329007/135386584-14bac1a4-8f00-4fd5-8755-f3c50431d975.png)
![rewardsupdates copy 6](https://user-images.githubusercontent.com/10329007/135386585-ed451403-31d0-44fc-9adf-60c47098e54c.png)
![rewardsupdates copy 14](https://user-images.githubusercontent.com/10329007/135386588-cda089ee-6ab1-46fc-8b20-512b1b914409.png)
![rewardsupdates copy 15](https://user-images.githubusercontent.com/10329007/135386589-35f2d546-c90d-4e32-b7d5-e1d9dc73c425.png)
![rewardsupdates copy 16](https://user-images.githubusercontent.com/10329007/135386590-cf2cb77b-caa7-4a05-9204-4dec007e823d.png)
![rewardsupdates copy 17](https://user-images.githubusercontent.com/10329007/135386592-2c5f826b-568c-402e-834c-171c399f2228.png)
![rewardsupdateslightlines-01 16](https://user-images.githubusercontent.com/10329007/135386596-5f30ccae-abc3-4179-b537-9de6f3420d42.png)

**Comment by kelcie33** [comment]
![Frame 24](https://user-images.githubusercontent.com/10329007/136481543-cc0daae8-6962-4eff-a00e-6bd85677c44b.png)
![lineabstractmultidotssmall-01 2](https://user-images.githubusercontent.com/10329007/136481548-81ea9586-7fc8-4d02-8754-1271f19d810e.png)
![Frame 36](https://user-images.githubusercontent.com/10329007/136481549-f65b676f-671e-4fb5-817a-21ebf7dcf94c.png)
![lineabstractmultidotssmall-01 11](https://user-images.githubusercontent.com/10329007/136481550-72b9f9d0-c642-4456-ad82-c02b7aa40b27.png)
![Frame 143](https://user-images.githubusercontent.com/10329007/136481551-8fb711ce-5857-41ce-adab-1ad2b5826864.png)
![lineabstractmultidotssmall-01 12](https://user-images.githubusercontent.com/10329007/136481552-3f4ebacc-c991-4dcd-bba9-661c578cf799.png)
![Frame 153](https://user-images.githubusercontent.com/10329007/136481553-2b6dcf3f-405c-486f-a6e1-cc08b075b895.png)
![lineabstractmultidotssmall-01 13](https://user-images.githubusercontent.com/10329007/136481555-7c7e0e63-fc73-49cb-9f22-c43b0734f89d.png)
![Frame 161](https://user-images.githubusercontent.com/10329007/136481558-d89d498a-3e39-4260-9b35-4a9219dab864.png)
![lineabstractmultidotssmall-01 14](https://user-images.githubusercontent.com/10329007/136481560-4951979f-d94d-409a-817b-3bf9c0768202.png)
![lineabstractmultidotssmall-01 15](https://user-images.githubusercontent.com/10329007/136481561-b9fd2fe4-1ac7-4f72-af6c-721345471367.png)
![Frame 169](https://user-images.githubusercontent.com/10329007/136481562-e999e31b-27e5-4599-8ab6-1fff913d3a6f.png)

**Comment by kelcie33** [comment]
![Frame 167](https://user-images.githubusercontent.com/10329007/136481597-42360822-73f0-4b37-860b-e12a8776331d.png)
![multicolororbit-01 14](https://user-images.githubusercontent.com/10329007/136481600-17e42455-52cd-43e6-adae-13b9a70b4d61.png)
![Frame 159](https://user-images.githubusercontent.com/10329007/136481602-7786102d-54da-4d9f-9785-650a88194d6f.png)
![multicolororbit-01 13](https://user-images.githubusercontent.com/10329007/136481603-c5a84c7c-668d-4fda-843c-7a6effc46cdb.png)
![Frame 151](https://user-images.githubusercontent.com/10329007/136481605-f85ce912-33f3-4a36-9ee2-34f884d3f6b5.png)
![multicolororbit-01 12](https://user-images.githubusercontent.com/10329007/136481607-c7e059e0-c24d-45b8-a7bb-596067a83686.png)
![Frame 142](https://user-images.githubusercontent.com/10329007/136481610-51fb8e34-3176-43f1-acbc-e9f06500bc80.png)
![multicolororbit-01 11](https://user-images.githubusercontent.com/10329007/136481611-c64854e0-79e7-480f-8aaf-3e890f658a25.png)
![Frame 136](https://user-images.githubusercontent.com/10329007/136481612-75ae8154-8670-4d66-b62a-b4d5f3bdcb50.png)
![multicolororbit-01 3](https://user-images.githubusercontent.com/10329007/136481615-f019f403-0098-43fe-82b2-cd86cb3b0ae6.png)
![Frame 26](https://user-images.githubusercontent.com/10329007/136481617-326d5929-e9fd-443f-bd03-088ee234c3e8.png)
![multicolororbit-01 2](https://user-images.githubusercontent.com/10329007/136481619-3d54491e-be6f-4cfd-9bd3-3530d73143d8.png)

**Comment by kelcie33** [comment]
![lineabstractmulti3color-01 2](https://user-images.githubusercontent.com/10329007/136481644-94fee1b2-0a6e-4f86-87f1-448b24b845d2.png)
![abstractlinesSquare-01 2](https://user-images.githubusercontent.com/10329007/136481647-3c56f7ea-02e8-4353-91fe-72ba742b81b5.png)
![lineabstractmulti3color-01 3](https://user-images.githubusercontent.com/10329007/136481649-182ed547-3959-4ed4-a290-fd2bda6b0362.png)
![abstractlinesSquare-01 18](https://user-images.githubusercontent.com/10329007/136481651-f750343d-4b78-4b94-9e56-8231855cd04d.png)
![lineabstractmulti3color-01 11](https://user-images.githubusercontent.com/10329007/136481652-085c50d3-01dc-4c54-a514-6d8f21f5bab4.png)
![abstractlinesSquare-01 19](https://user-images.githubusercontent.com/10329007/136481653-946fb39f-6431-46ac-aaef-d0cf39abddf8.png)
![lineabstractmulti3color-01 12](https://user-images.githubusercontent.com/10329007/136481654-61bb6ffb-7dcf-4851-9b78-50eb8d4083d1.png)
![abstractlinesSquare-01 20](https://user-images.githubusercontent.com/10329007/136481656-c505bfda-c6ed-4187-919f-31adf2962900.png)
![lineabstractmulti3color-01 13](https://user-images.githubusercontent.com/10329007/136481658-05af3fc8-4525-4ca0-89e4-be0a633f0dd8.png)
![abstractlinesSquare-01 21](https://user-images.githubusercontent.com/10329007/136481659-facc097b-a4fe-4bc2-b5e1-c428ac017c83.png)
![lineabstractmulti3color-01 14](https://user-images.githubusercontent.com/10329007/136481662-6c7a5600-7468-41d0-b1d3-81a1bad724d5.png)
![abstractlinesSquare-01 22](https://user-images.githubusercontent.com/10329007/136481663-1d34a991-d9c5-4fa1-9341-980825f55876.png)

**Comment by kelcie33** [comment]
![Frame 108](https://user-images.githubusercontent.com/10329007/136481781-8cd05884-163a-48ec-8fd5-558a4deb2538.png)
![Frame 29](https://user-images.githubusercontent.com/10329007/136481785-835834bc-d111-46fb-9916-71d36e563049.png)
![rewardsupdateslightlines-01 6](https://user-images.githubusercontent.com/10329007/136481788-44c92d75-1a6e-42b7-8328-807440765b01.png)
![Frame 132](https://user-images.githubusercontent.com/10329007/136481789-5ad765db-427b-4efe-b8ea-53bd3965ab83.png)
![Frame 145](https://user-images.githubusercontent.com/10329007/136481790-dcd9d8b4-86ec-44e8-8388-d957123a35d4.png)
![Frame 138](https://user-images.githubusercontent.com/10329007/136481792-a9dab5eb-fc7b-405a-9002-37e563b60f98.png)
![rewardsupdateslightlines-01 14](https://user-images.githubusercontent.com/10329007/136481794-af34a6a2-1400-498d-90bc-7cd618e75a99.png)
![Frame 147](https://user-images.githubusercontent.com/10329007/136481797-1de20cd8-f6a2-4122-a1be-89ff7beeeef5.png)
![rewardsupdateslightlines-01 15](https://user-images.githubusercontent.com/10329007/136481798-8508ecd2-ae01-4e70-bdec-ee66b42d77ca.png)
![Frame 155](https://user-images.githubusercontent.com/10329007/136481799-251be11f-605f-4587-91eb-b66d80f74acd.png)
![rewardsupdateslightlines-01 16](https://user-images.githubusercontent.com/10329007/136481800-60558320-41b6-47a8-b5b9-10aec7d27c27.png)
![Frame 163](https://user-images.githubusercontent.com/10329007/136481802-ba9623bd-a783-4020-b3a8-3a654e23798e.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137245753-fbad840f-ada1-4061-a7c3-7cc121f85a8f.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137245935-32852712-fdaf-4f07-b151-784341c6c4b4.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137246019-419ede9b-a980-4eb9-965d-ac146464a447.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137246076-ca8b0f03-0127-42bf-a0bd-34b6624bfeb2.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137246122-09b1353d-f634-4d65-8892-021103655059.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137246176-2181debc-fc99-4d7d-a743-475a64e1d090.png)

**Comment by kelcie33** [comment]
![image](https://user-images.githubusercontent.com/10329007/137246263-c41dcd0d-45fb-4fab-9425-fa0ae886be16.png)

**Comment by kelcie33** [comment]
moved to drive
